config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'application#index'
  resources :about
  resources :services
  resources :bookings
  resources :technicians
  resources :testimonials
  resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index; end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def index
    # render 'application/index/index'
  end

  # def about
  #   # render 'application/about/about'
  # end

  # def services
  #   # render 'application/services/services'
  # end

  # def booking
  #   render 'application/booking/booking'
  # end

  # def technicians
  #   render 'application/technicians/technicians'
  # end

  # def testimonial
  #   render 'application/testimonial/testimonial'
  # end

  # def contact
  #   render 'application/contact/contact'
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index; end
end

app/controllers/technicians_controller.rb
class TechniciansController < ApplicationController
  def index
  end
end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
  def index
  end
end
 

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    return unless current_page?(path)

    'active'
  end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/technicians_helper.rb
module TechniciansHelper
end

app/helpers/testimonial_helper.rb
module TestimonialHelper
end

app/views/about/index.html.erb
<%= render 'page_header', location: 'About Us'%>

<!-- Service Start -->
<%= render 'partial/service_start' %>
<!-- Service End -->

<!-- About Start -->
<%= render 'partial/about' %>
<!-- About End -->

<!-- Fact Start -->
<%= render 'partial/fact' %>
<!-- Fact End -->

<!-- Team Start -->
<%= render 'partial/team', amount: 4 %>
<!-- Team End -->

app/views/application/_carousel.html.erb
<div class="container-fluid p-0 mb-5">
  <div id="header-carousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="w-100" src="<%= image_url('carousel-bg-1.jpg') %>" alt="Image">
        <div class="carousel-caption d-flex align-items-center">
          <div class="container">
            <div class="row align-items-center justify-content-center justify-content-lg-start">
              <div class="col-10 col-lg-7 text-center text-lg-start">
                <h6 class="text-white text-uppercase mb-3 animated slideInDown">// Car Servicing //</h6>
                <h1 class="display-3 text-white mb-4 pb-3 animated slideInDown">Qualified Car Repair Service Center</h1>
                <a href="" class="btn btn-primary py-3 px-5 animated slideInDown">Learn More<i class="fa fa-arrow-right ms-3"></i></a>
              </div>
              <div class="col-lg-5 d-none d-lg-flex animated zoomIn">
                <img class="img-fluid" src="<%= image_url('carousel-1.png') %>" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="carousel-item">
        <img class="w-100" src="<%= image_url('carousel-bg-2.jpg') %>" alt="Image">
        <div class="carousel-caption d-flex align-items-center">
          <div class="container">
            <div class="row align-items-center justify-content-center justify-content-lg-start">
              <div class="col-10 col-lg-7 text-center text-lg-start">
                <h6 class="text-white text-uppercase mb-3 animated slideInDown">// Car Servicing //</h6>
                <h1 class="display-3 text-white mb-4 pb-3 animated slideInDown">Qualified Car Wash Service Center</h1>
                <a href="" class="btn btn-primary py-3 px-5 animated slideInDown">Learn More<i class="fa fa-arrow-right ms-3"></i></a>
              </div>
              <div class="col-lg-5 d-none d-lg-flex animated zoomIn">
                <img class="img-fluid" src="<%= image_url('carousel-2.png') %>" alt="">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <button class="carousel-control-prev" type="button" data-bs-target="#header-carousel"
      data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#header-carousel"
      data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
    
  </div>
</div>

app/views/application/_page_header.html.erb
<!-- Page Header Start -->
<div class="container-fluid page-header mb-5 p-0" style="background-image: url(<%= asset_url('carousel-bg-1.jpg') %>);">
  <div class="container-fluid page-header-inner py-5">
    <div class="container text-center">
      <h1 class="display-3 text-white mb-3 animated slideInDown"><%= location %></h1>
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb justify-content-center text-uppercase">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="#">Pages</a></li>
          <li class="breadcrumb-item text-white active" aria-current="page"><%= location %></li>
        </ol>
      </nav>
    </div>
  </div>
</div>
<!-- Page Header End -->

app/views/application/contact/contact.html.erb
<%= render 'page_header', location: 'Contact' %>
<div class="container-xxl py-5">
  <div class="container">
    <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
      <h6 class="text-primary text-uppercase">// Contact Us //</h6>
      <h1 class="mb-5">Contact For Any Query</h1>
    </div>
    <div class="row g-4">
      <div class="col-12">
        <div class="row gy-4">
          <div class="col-md-4">
            <div class="bg-light d-flex flex-column justify-content-center p-4">
              <h5 class="text-uppercase">// Booking //</h5>
              <p class="m-0"><i class="fa fa-envelope-open text-primary me-2"></i>book@example.com</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="bg-light d-flex flex-column justify-content-center p-4">
              <h5 class="text-uppercase">// General //</h5>
              <p class="m-0"><i class="fa fa-envelope-open text-primary me-2"></i>info@example.com</p>
            </div>
          </div>
          <div class="col-md-4">
            <div class="bg-light d-flex flex-column justify-content-center p-4">
              <h5 class="text-uppercase">// Technical //</h5>
              <p class="m-0"><i class="fa fa-envelope-open text-primary me-2"></i>tech@example.com</p>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6 wow fadeIn" data-wow-delay="0.1s">
        <iframe class="position-relative rounded w-100 h-100"
          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
          frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
          tabindex="0"></iframe>
      </div>
      <div class="col-md-6">
        <div class="wow fadeInUp" data-wow-delay="0.2s">
          <p class="mb-4">The contact form is currently inactive. Get a functional and working contact form with Ajax & PHP in a few minutes. Just copy and paste the files, add a little code and you're done. <a href="https://htmlcodex.com/contact-form">Download Now</a>.</p>
          <form>
            <div class="row g-3">
              <div class="col-md-6">
                <div class="form-floating">
                  <input type="text" class="form-control" id="name" placeholder="Your Name">
                  <label for="name">Your Name</label>
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-floating">
                  <input type="email" class="form-control" id="email" placeholder="Your Email">
                  <label for="email">Your Email</label>
                </div>
              </div>
              <div class="col-12">
                <div class="form-floating">
                  <input type="text" class="form-control" id="subject" placeholder="Subject">
                  <label for="subject">Subject</label>
                </div>
              </div>
              <div class="col-12">
                <div class="form-floating">
                  <textarea class="form-control" placeholder="Leave a message here" id="message" style="height: 100px"></textarea>
                  <label for="message">Message</label>
                </div>
              </div>
              <div class="col-12">
                <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/index.html.erb
<!DOCTYPE html>
<html lang="en">
<%# 
<head>
  <meta charset="utf-8">
  <title>CarServ - Car Repair HTML Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicon -->
  
</head> %>

<body>
  <!-- Carousel Start -->
  <%= render 'carousel' %>
  <!-- Carousel End -->

  <!-- Service Start -->
  <%= render 'partial/service_start' %>
  <!-- Service End -->

  <!-- About Start -->
  <%= render 'partial/about' %>
  <!-- About End -->

  <!-- Fact Start -->
  <%= render 'partial/fact' %>
  <!-- Fact End -->

  <!-- Service Start -->
  <%= render 'partial/service' %>
  <!-- Service End -->

  <!-- Booking Start -->
  <%= render 'partial/booking' %>
  <!-- Booking End -->

  <!-- Team Start -->
  <%= render 'partial/team', amount: 4 %>
  <!-- Team End -->

  <!-- Testimonial Start -->
  <%= render 'partial/testimonial' %>
  <!-- Testimonial End -->


  
</body>

</html>

app/views/application/technicians/technicians.html.erb
<%= render 'page_header', location: 'Technicians' %>
<%= render 'team/team', amount: 8 %>

app/views/application/testimonial/testimonial.html.erb
<%= render 'page_header', location: 'Testimonial' %>
<%= render 'testimonial/testimonial' %>

app/views/navbar/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center px-4 px-lg-5" do %>
    <h2 class="m-0 text-primary"><i class="fa fa-car me-3"></i>CarServ</h2>
  <% end %>
  <%# <a href="<index>" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
    <h2 class="m-0 text-primary"><i class="fa fa-car me-3"></i>CarServ</h2>
  </a> %>
  <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto p-4 p-lg-0">
      <%# <a href="/" class="nav-item nav-link active">Home</a> %>
      <%= link_to 'Home', root_path, class: "nav-item nav-link #{active?(root_path)}" %>
      <%= link_to 'About', about_path, class: "nav-item nav-link #{active?(about_path)}" %>
      <%# <a href="/about" class="nav-item nav-link">About</a> %>
      <%= link_to 'Services', services_path, class: "nav-item nav-link #{active?(services_path)}" %>
      <%# <a href="/service" class="nav-item nav-link">Services</a> %>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
        <div class="dropdown-menu fade-up m-0">
          <%= link_to 'Booking', booking_path, class: 'dropdown-item'%>
          <%# <a href="/booking" class="dropdown-item">Booking</a> %>
          <%= link_to 'Technicians', technicians_path, class: 'dropdown-item' %>
          <%# <a href="/team" class="dropdown-item">Technicians</a> %>
          <%= link_to 'Testimonial', testimonial_path, class: 'dropdown-item' %>
          <%# <a href="/testimonial" class="dropdown-item">Testimonial</a> %>
          <%# <a href="/404" class="dropdown-item">404 Page</a> %>
        </div>
      </div>
      <%= link_to 'Contact', contact_path, class: 'nav-item nav-link' %>
      <%# <a href="contact" class="nav-item nav-link">Contact</a> %>
    </div>
    <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Get A Quote<i class="fa fa-arrow-right ms-3"></i></a>
  </div>
</nav>

app/views/partial/_about.html.erb
<div class="container-xxl py-5">
  <div class="container">
    <div class="row g-5">
      <div class="col-lg-6 pt-4" style="min-height: 400px;">
        <div class="position-relative h-100 wow fadeIn" data-wow-delay="0.1s">
          <img class="position-absolute img-fluid w-100 h-100" src="<%= image_url('about.jpg') %>" style="object-fit: cover;" alt="">
          <div class="position-absolute top-0 end-0 mt-n4 me-n4 py-4 px-5" style="background: rgba(0, 0, 0, .08);">
            <h1 class="display-4 text-white mb-0">15 <span class="fs-4">Years</span></h1>
            <h4 class="text-white">Experience</h4>
          </div>
        </div>
      </div>
      <div class="col-lg-6">
        <h6 class="text-primary text-uppercase">// About Us //</h6>
        <h1 class="mb-4"><span class="text-primary">CarServ</span> Is The Best Place For Your Auto Care</h1>
        <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum sit. Aliqu diam amet diam et eos. Clita erat ipsum et lorem et sit, sed stet lorem sit clita duo justo magna dolore erat amet</p>
        <div class="row g-4 mb-3 pb-3">
          <div class="col-12 wow fadeIn" data-wow-delay="0.1s">
            <div class="d-flex">
              <div class="bg-light d-flex flex-shrink-0 align-items-center justify-content-center mt-1" style="width: 45px; height: 45px;">
                <span class="fw-bold text-secondary">01</span>
              </div>
              <div class="ps-3">
                <h6>Professional & Expert</h6>
                <span>Diam dolor diam ipsum sit amet diam et eos</span>
              </div>
            </div>
          </div>
          <div class="col-12 wow fadeIn" data-wow-delay="0.3s">
            <div class="d-flex">
              <div class="bg-light d-flex flex-shrink-0 align-items-center justify-content-center mt-1" style="width: 45px; height: 45px;">
                <span class="fw-bold text-secondary">02</span>
              </div>
              <div class="ps-3">
                <h6>Quality Servicing Center</h6>
                <span>Diam dolor diam ipsum sit amet diam et eos</span>
              </div>
            </div>
          </div>
          <div class="col-12 wow fadeIn" data-wow-delay="0.5s">
            <div class="d-flex">
              <div class="bg-light d-flex flex-shrink-0 align-items-center justify-content-center mt-1" style="width: 45px; height: 45px;">
                <span class="fw-bold text-secondary">03</span>
              </div>
              <div class="ps-3">
                <h6>Awards Winning Workers</h6>
                <span>Diam dolor diam ipsum sit amet diam et eos</span>
              </div>
            </div>
          </div>
        </div>
        <a href="" class="btn btn-primary py-3 px-5">Read More<i class="fa fa-arrow-right ms-3"></i></a>
      </div>
    </div>
  </div>
</div>

app/views/partial/_booking.html.erb
<div class="container-fluid bg-secondary booking my-5 wow fadeInUp" data-wow-delay="0.1s">
  <div class="container">
    <div class="row gx-5">
      <div class="col-lg-6 py-5">
        <div class="py-5">
          <h1 class="text-white mb-4">Certified and Award Winning Car Repair Service Provider</h1>
          <p class="text-white mb-0">Eirmod sed tempor lorem ut dolores. Aliquyam sit sadipscing kasd ipsum. Dolor ea et dolore et at sea ea at dolor, justo ipsum duo rebum sea invidunt voluptua. Eos vero eos vero ea et dolore eirmod et. Dolores diam duo invidunt lorem. Elitr ut dolores magna sit. Sea dolore sanctus sed et. Takimata takimata sanctus sed.</p>
        </div>
      </div>
      <div class="col-lg-6">
        <div class="bg-primary h-100 d-flex flex-column justify-content-center text-center p-5 wow zoomIn" data-wow-delay="0.6s">
          <h1 class="text-white mb-4">Book For A Service</h1>
          <form>
            <div class="row g-3">
              <div class="col-12 col-sm-6">
                <input type="text" class="form-control border-0" placeholder="Your Name" style="height: 55px;">
              </div>
              <div class="col-12 col-sm-6">
                <input type="email" class="form-control border-0" placeholder="Your Email" style="height: 55px;">
              </div>
              <div class="col-12 col-sm-6">
                <select class="form-select border-0" style="height: 55px;">
                  <option selected>Select A Service</option>
                  <option value="1">Service 1</option>
                  <option value="2">Service 2</option>
                  <option value="3">Service 3</option>
                </select>
              </div>
              <div class="col-12 col-sm-6">
                <div class="date" id="date1" data-target-input="nearest">
                  <input type="text"
                    class="form-control border-0 datetimepicker-input"
                    placeholder="Service Date" data-target="#date1" data-toggle="datetimepicker" style="height: 55px;">
                </div>
              </div>
              <div class="col-12">
                <textarea class="form-control border-0" placeholder="Special Request"></textarea>
              </div>
              <div class="col-12">
                <button class="btn btn-secondary w-100 py-3" type="submit">Book Now</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partial/_fact.html.erb
<div class="container-fluid fact bg-dark my-5 py-5">
  <div class="container">
  <div class="row g-4">
    <div class="col-md-6 col-lg-3 text-center wow fadeIn" data-wow-delay="0.1s">
    <i class="fa fa-check fa-2x text-white mb-3"></i>
    <h2 class="text-white mb-2" data-toggle="counter-up">1234</h2>
    <p class="text-white mb-0">Years Experience</p>
    </div>
    <div class="col-md-6 col-lg-3 text-center wow fadeIn" data-wow-delay="0.3s">
    <i class="fa fa-users-cog fa-2x text-white mb-3"></i>
    <h2 class="text-white mb-2" data-toggle="counter-up">1234</h2>
    <p class="text-white mb-0">Expert Technicians</p>
    </div>
    <div class="col-md-6 col-lg-3 text-center wow fadeIn" data-wow-delay="0.5s">
    <i class="fa fa-users fa-2x text-white mb-3"></i>
    <h2 class="text-white mb-2" data-toggle="counter-up">1234</h2>
    <p class="text-white mb-0">Satisfied Clients</p>
    </div>
    <div class="col-md-6 col-lg-3 text-center wow fadeIn" data-wow-delay="0.7s">
    <i class="fa fa-car fa-2x text-white mb-3"></i>
    <h2 class="text-white mb-2" data-toggle="counter-up">1234</h2>
    <p class="text-white mb-0">Compleate Projects</p>
    </div>
  </div>
  </div>
</div>

app/views/partial/_footer.html.erb
<div class="container-fluid bg-dark text-light footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
  <div class="container py-5">
    <div class="row g-5">
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Address</h4>
        <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>123 Street, New York, USA</p>
        <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p>
        <p class="mb-2"><i class="fa fa-envelope me-3"></i>info@example.com</p>
        <div class="d-flex pt-2">
          <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
          <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
          <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
          <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Opening Hours</h4>
        <h6 class="text-light">Monday - Friday:</h6>
        <p class="mb-4">09.00 AM - 09.00 PM</p>
        <h6 class="text-light">Saturday - Sunday:</h6>
        <p class="mb-0">09.00 AM - 12.00 PM</p>
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Services</h4>
        <a class="btn btn-link" href="">Diagnostic Test</a>
        <a class="btn btn-link" href="">Engine Servicing</a>
        <a class="btn btn-link" href="">Tires Replacement</a>
        <a class="btn btn-link" href="">Oil Changing</a>
        <a class="btn btn-link" href="">Vacuam Cleaning</a>
      </div>
      <div class="col-lg-3 col-md-6">
        <h4 class="text-light mb-4">Newsletter</h4>
        <p>Dolor amet sit justo amet elitr clita ipsum elitr est.</p>
        <div class="position-relative mx-auto" style="max-width: 400px;">
          <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
          <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="copyright">
      <div class="row">
        <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
          &copy; <a class="border-bottom" href="#">Your Site Name</a>, All Right Reserved.

          <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
          Designed By <a class="border-bottom" href="https://htmlcodex.com">HTML Codex</a>
        </div>
        <div class="col-md-6 text-center text-md-end">
          <div class="footer-menu">
            <a href="">Home</a>
            <a href="">Cookies</a>
            <a href="">Help</a>
            <a href="">FQAs</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow sticky-top p-0">
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center px-4 px-lg-5" do %>
    <h2 class="m-0 text-primary"><i class="fa fa-car me-3"></i>Tazz Garage</h2>
  <% end %>
  <%# <a href="<index>" class="navbar-brand d-flex align-items-center px-4 px-lg-5">
    <h2 class="m-0 text-primary"><i class="fa fa-car me-3"></i>CarServ</h2>
  </a> %>
  <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarCollapse">
    <div class="navbar-nav ms-auto p-4 p-lg-0">
      <%# <a href="/" class="nav-item nav-link active">Home</a> %>
      <%= link_to 'Home', root_path, class: "nav-item nav-link #{active?(root_path)}" %>
      <%= link_to 'About', about_index_path, class: "nav-item nav-link #{active?(about_index_path)}" %>
      <%# <a href="/about" class="nav-item nav-link">About</a> %>
      <%= link_to 'Services', services_path, class: "nav-item nav-link #{active?(services_path)}" %>
      <%# <a href="/service" class="nav-item nav-link">Services</a> %>
      <div class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Pages</a>
        <div class="dropdown-menu fade-up m-0">
          <%= link_to 'Booking', bookings_path, class: 'dropdown-item'%>
          <%# <a href="/booking" class="dropdown-item">Booking</a> %>
          <%= link_to 'Technicians', technicians_path, class: 'dropdown-item' %>
          <%# <a href="/team" class="dropdown-item">Technicians</a> %>
          <%= link_to 'Testimonial', testimonials_path, class: 'dropdown-item' %>
          <%# <a href="/testimonial" class="dropdown-item">Testimonial</a> %>
          <%# <a href="/404" class="dropdown-item">404 Page</a> %>
        </div>
      </div>
      <%= link_to 'Contact', contacts_path, class: 'nav-item nav-link' %>
      <%# <a href="contact" class="nav-item nav-link">Contact</a> %>
    </div>
    <a href="" class="btn btn-primary py-4 px-lg-5 d-none d-lg-block">Get A Quote<i class="fa fa-arrow-right ms-3"></i></a>
  </div>
</nav>

app/views/partial/_service_start.html.erb
<div class="container-xxl py-5">
	<div class="container">
		<div class="row g-4">
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
				<div class="d-flex py-5 px-4">
						<i class="fa fa-certificate fa-3x text-primary flex-shrink-0"></i>
						<div class="ps-4">
							<h5 class="mb-3">Quality Servicing</h5>
							<p>Diam dolor diam ipsum sit amet diam et eos erat ipsum</p>
							<a class="text-secondary border-bottom" href="">Read More</a>
						</div>
				</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.3s">
					<div class="d-flex bg-light py-5 px-4">
						<i class="fa fa-users-cog fa-3x text-primary flex-shrink-0"></i>
						<div class="ps-4">
							<h5 class="mb-3">Expert Workers</h5>
							<p>Diam dolor diam ipsum sit amet diam et eos erat ipsum</p>
							<a class="text-secondary border-bottom" href="">Read More</a>
						</div>
					</div>
			</div>
			<div class="col-lg-4 col-md-6 wow fadeInUp" data-wow-delay="0.5s">
				<div class="d-flex py-5 px-4">
						<i class="fa fa-tools fa-3x text-primary flex-shrink-0"></i>
						<div class="ps-4">
							<h5 class="mb-3">Modern Equipment</h5>
							<p>Diam dolor diam ipsum sit amet diam et eos erat ipsum</p>
							<a class="text-secondary border-bottom" href="">Read More</a>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/partial/shared/_spinner.html.erb
<!-- Spinner Start -->
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
  <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
    <span class="sr-only">Loading...</span>
  </div>
</div>
<!-- Spinner End -->